### ISSUE TITLE
adjust chat displays for better flow/functionality

### ISSUE THREAD

**Issue by asehlers** [abruestle/ShiftShare#14]
right now the chat is defaulting to original comments when it expands to display. Would make more sense for it to display recent. Additionally chat background is sometimes displaying without the chat textbox # #

**Comment by abruestle** [comment]
The code for scrolling to the bottom is :
  $("#chat").scrollTop($("#chat")[0].scrollHeight);
I will put it on a timer so it waits for the transition to finish before it does that. ...The chat background thing I will have to think on why it does that.

**Comment by abruestle** [comment]
Fixed!
